### ISSUE TITLE
Mute/unmute does not seem to be working with microsoft teams.

### ISSUE THREAD

**Issue by rafek1241** [aderusha/BoseQCMicMute#2]
**nitpick:** Mute/unmute does not seem to be working with microsoft teams. It looks like they are working only with windows microphone settings.

**Comment by aderusha** [comment]
There's two components here, one is picking up the media keys, the next is sending the microphone mute command.  When you press the button, do you see a notification displayed?

Trying to figure out if it's a) not picking up the media keys or b) picking them up but not doing anything in response.

Keep in mind that there are at least two bluetooth profiles of interest, if you (or Windows) switch to the handset profile, the media keys may no longer be sent by the headset.  In this case, the QC35 II and 45s have a mute function which is triggered by pressing both vol+ and vol-.

Teams is my primary test case and, on my Win 11 system, it works reliably.

**Comment by rafek1241** [comment]
I have windows 10 and qc35II. I used middle button in headphones and maybe that was the issue..

**Comment by aderusha** [comment]
What happens when you press the middle button? 

The flow should be something like this:
1. You press middle button
2. QC sends media key via bluetooth
3. BoseQCMicMute detects media key and issues notification (beep, icon change, toast, etc)
4. BoseQCMicMute sends commands to mute/unmute all recording devices.

Do you get the notification at step 3?  Or does that never get picked up?

**Comment by rafek1241** [comment]
Nope, I didn't receive any notification.

**Comment by aderusha** [comment]
In that event, you are not picking up the media keys.  Either they aren't being sent as you are in the wrong bluetooth profile (in which case, vol+ and vol- together should mute), or they are being sent and some other software on your system is grabbing those events before we can get at them (typically, media players like Spotify).  [Check this article](https://www.askvg.com/fix-media-keys-not-working-in-spotify-itunes-and-other-media-players/) on how you might deal with that.

**Comment by aderusha** [comment]
I've just released a new version that is a lot more aggressive about grabbing and re-grabbing control over the media keys.  The new version will attempt to re-establish keyboard hooks every 15 seconds, and also every time you click on the tray icon.

@rafek1241 - can you give this a shot with Teams?

**Comment by rafek1241** [comment]
Will check it tomorrow, thanks

**Comment by rafek1241** [comment]
I changed windows to `11` and it seems to still not working for MS teams :/

**Comment by aderusha** [comment]
Well that's no fun.  Does it work at all?  Do you get any response from pressing the MFB button on the headset without Teams running?  How about 15 seconds after Teams launches?

**Comment by rafek1241** [comment]
When I click on icon on tray it works fine. When I do this via middle button in headphones, it does not work at all

**Comment by aderusha** [comment]
OK here's one more thought - are your headphones attached to just your PC, or are they also connected to a phone/etc (meaning, are you using the Bose ability to connect to two devices at the same time?)

**Comment by rafek1241** [comment]
There is connection to phone as well

**Comment by aderusha** [comment]
Is there any change in behavior if you disconnect your phone, so the headset is only connected to your windows machine?  If so, there might be a solution to this but it's going to take a bit of hacking.

**Comment by rafek1241** [comment]
I don't have time to check that. Feel free to close this issue cause I don't need it that much to make effort with finding a root cause and fixing a bug.
